import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <meta charSet='UTF-8' />
        <meta httpEquiv='x-ua-compatible' content='ie=edge' />
        <title>Charina – Nonprofit and Charity HTML5 Template</title>
        <meta name='description' content='' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/*Favicon*/}
        <link
          rel='icon'
          type='image/png'
          sizes='56x56'
          href='assets/images/fav-icon/icon.png'
        />
        {/*bootstrap CSS*/}
        <link
          rel='stylesheet'
          href='assets/css/bootstrap.min.css'
          type='text/css'
          media='all'
        />
        {/*carousel CSS*/}
        <link
          rel='stylesheet'
          href='assets/css/owl.carousel.min.css'
          type='text/css'
          media='all'
        />
        {/*animate CSS*/}
        <link
          rel='stylesheet'
          href='assets/css/animate.css'
          type='text/css'
          media='all'
        />
        {/*animated-text CSS*/}
        <link
          rel='stylesheet'
          href='assets/css/animated-text.css'
          type='text/css'
          media='all'
        />
        {/*font-awesome CSS*/}
        <link
          rel='stylesheet'
          href='assets/css/all.min.css'
          type='text/css'
          media='all'
        />
        {/*font-flaticon CSS*/}
        <link
          rel='stylesheet'
          href='assets/css/flaticon.css'
          type='text/css'
          media='all'
        />
        {/*theme-default CSS*/}
        <link
          rel='stylesheet'
          href='assets/css/theme-default.css'
          type='text/css'
          media='all'
        />
        {/*meanmenu CSS*/}
        <link
          rel='stylesheet'
          href='assets/css/meanmenu.min.css'
          type='text/css'
          media='all'
        />
        {/*Main Style CSS*/}
        <link rel='stylesheet' href='style.css' type='text/css' media='all' />
        {/*transitions CSS*/}
        <link
          rel='stylesheet'
          href='assets/css/owl.transitions.css'
          type='text/css'
          media='all'
        />
        {/*venobox CSS*/}
        <link
          rel='stylesheet'
          href='venobox/venobox.css'
          type='text/css'
          media='all'
        />
        {/*responsive CSS*/}
        <link
          rel='stylesheet'
          href='assets/css/responsive.css'
          type='text/css'
          media='all'
        />
        {/*modernizr js*/}
        {/*bootstrap icons*/}
        <link
          rel='stylesheet'
          href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css'
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
